name: Deploy Infrastructure

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-deploy
          aws-region: eu-central-1

      - name: Deploy CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: zota-asset-proxy-stack
          template: infrastructure/template.yaml
          no-fail-on-empty-changeset: "1"
          create-stack-if-not-exists: "true" 
          parameter-overrides: >-
            ImageTag=${{ inputs.image_tag }},
            ProjectName=zota-asset-proxy
          capabilities: CAPABILITY_NAMED_IAM